name: Open Pull Request to main

on:
  push:
    branches:
      - "**" # Trigger the workflow on pushes to the main branch
      - '!master' # Except master
      - '!prod' # Except master
      - '!development' # Except master
      - '!main' # Except main

permissions:
  contents: write
  pull-requests: write  

jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: pull-request
        id: pull-request
        uses: repo-sync/pull-request@v2
        continue-on-error: true
        with:
          destination_branch: "development"
          github_token: ${{ secrets.GT_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[#PR] ${{ github.event.head_commit.message }}"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_reviewer: "OtavioFreire"
